# Redirector extension configuration file

#301:
#  '/my-custom-page': '/redirect-here'
#  '/another-redirect': 'https://google.com'

#302:
#  '/redirect-with-another-status-code': '/redirect-to-another-page'
